
# for openldap
# in this most recent config, used live certificates and that seemed to work.
# it does generate dhpram.pem file in the /volumes/npm/letsencrypt folder since that is the volume for certs. The certificate path from there onwards is mentioned in the filename environmental variable like-
#    LDAP_TLS_CRT_FILENAME: /live/${npm_XX}/cert.pem

# for phpldapadmin, it used the certificate links to the let's encrypt certificates.

# for NPM
# entry ldap.${DOMAIN}.${TLD} needed https at forward using "18443" forward with port 80 did not work

# this worked, login with following credentials in the phpLDAPadmin
# cn=admin,dc=${DOMAIN},dc=${TLD}
# ${CHANGEME}

# cn=user-ro,dc=${DOMAIN},dc=${TLD}
# Passowrd ro_pass

# ref used was https://github.com/osixia/docker-openldap/issues/120
# and https://github.com/Ramhm/openldap/blob/master/docker-compose.yml 

# replace ${DOMAIN} ${CHANGEME} ${npm_XX} docker-network

version: '2'
services:
  openldap:
    image: osixia/openldap:1.1.8
    container_name: ldap_openldap
    volumes:
      #- /volumes/npm/letsencrypt/archive/${npm_XX}:/container/service/slapd/assets/certs/
      - /volumes/npm/letsencrypt:/container/service/slapd/assets/certs
      - /volumes/ldap/ldapData:/var/lib/ldap
      - /volumes/ldap/ldapConf:/etc/ldap/slapd.d

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "${DOMAIN}"
      LDAP_DOMAIN: "${DOMAIN}.${TLD}"
      LDAP_BASE_DN: dc=${DOMAIN},dc=${TLD}
      LDAP_ADMIN_USERNAME: ${ADMIN}
      LDAP_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${CONFIG_PASSWORD}
      LDAP_READONLY_USER: "false" #change this to true if using readonly username/password
      # LDAP_READONLY_USER_USERNAME: ro_user
      # LDAP_READONLY_USER_PASSWORD: ro_pass
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      #LDAP_TLS_CRT_FILENAME: cert1.pem
      #LDAP_TLS_KEY_FILENAME: privkey1.pem
      #LDAP_TLS_CA_CRT_FILENAME: fullchain1.pem
      LDAP_TLS_CRT_FILENAME: /live/${npm_XX}/cert.pem
      LDAP_TLS_KEY_FILENAME: /live/${npm_XX}/privkey.pem
      LDAP_TLS_CA_CRT_FILENAME: /live/${npm_XX}/fullchain.pem
      LDAP_TLS_VERIFY_CLIENT: "try"
      LDAP_TLS_ENFORCE: "false"
      LDAP_REPLICATION: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"

    stdin_open: true
    ports:
      - "${OPENLDAP_PORT}:636"
    hostname: "ldap_openldap"
    networks:
      - docker-network
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldap_phpldapadmin
    volumes:
      - /volumes/npm/letsencrypt:/container/service/phpldapadmin/assets/apache2/certs
      - /volumes/ldap/phpldapadmin:/var/www/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "true"
      PHPLDAPADMIN_HTTPS_CRT_FILENAME: "/live/${npm_XX}/cert.pem" #not sure why but openldap does not like quotes and phpldapadmin likes the string in quote as here
      PHPLDAPADMIN_HTTPS_KEY_FILENAME: "/live/${npm_XX}/privkey.pem"
      PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: "/live/${npm_XX}/fullchain.pem"
      PHPLDAPADMIN_LDAP_CLIENT_TLS: "false"
    ports:
      - "${LDAPADMIN_PORT}:443" #18443

    depends_on:
      - openldap
    hostname: "ldap_phpldapadmin"
    networks:
      - docker-network
volumes:
    ldapData:
    ldapConf:
networks:
  docker-network:
      external:
        name: docker-network

