# Ended up not using this since pihole.yml worked after changing the DNS on router to local network of host for Ubuntu on pihole.yml implementation.
# Note: 10.0.0.xxx is an example network, you must update all these to match your own.
# source: https://tonylawrence.com/posts/unix/synology/free-your-synology-ports/
# sudo docker network create —driver=macvlan —gateway=10.0.0.1 —subnet=10.0.0.0/24 —ip-range=10.0.0.192/28 -o parent=eth0 pihole_network

# to find network such as eth0 use following command
# sudo ls /sys/class/net # lists them all
# ubuntu is :  enp2s0

version: '2'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: doc4child.com             # <-- Update
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    networks:
      pihole_network:
        ipv4_address: 10.0.0.199   # <-- Update
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      ServerIP: 10.0.0.199         # <-- Update (match ipv4_address)
      VIRTUAL_HOST: pihole.doc4child.com  # <-- Update (match hostname + domainname)
      WEBPASSWORD: ""                   # <-- Add password (if required)
    restart: unless-stopped
    volumes:
      - /volume/pihole/volume:/etc/pihole:rw
      - /volume/pihole/config/hosts:/etc/hosts:ro
      - /volume/pihole/config/resolv.conf:/etc/resolv.conf:ro
      - /volume/pihole/config/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf:ro
networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: ovs_eth0
    ipam:
      config:
        - subnet: 10.0.0.0/24            # <-- Update
          gateway: 10.0.0.1              # <-- Update
          ip_range: 10.0.0.192/28        # <-- Update