version: '3.2'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
    
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /volumes/monitoring/prometheus/config:/etc/prometheus
      - /volumes/monitoring/prometheus:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /volumes/monitoring/grafana-data:/var/lib/grafana
    restart: unless-stopped
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - ${CADVISOR_PORT:-8080}: 8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro # changed this to rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro      
    
    devices:
      - /dev/kmsg
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'